name: Build & Auto-Version

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}-build${{ github.run_attempt }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Set version from Git tag if exists
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "Using Git tag version: $TAG_VERSION"
          mvn versions:set -DnewVersion=$TAG_VERSION -DgenerateBackupPoms=false

      - name: Set custom CI version if no Git tag
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          VERSION="1.0.0-${{ github.ref_name }}-${{ env.TIMESTAMP }}"
          echo "CI version: $VERSION"
          mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false

      - name: Build & Test
        run: mvn -B verify --file pom.xml

      - name: Show Final Version
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout
