name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.ref_name }}
      TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}-build${{ github.run_attempt }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Import GPG key
        run: echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Set version from tag
        run: |
          VERSION_CLEAN=${VERSION#v}
          echo "Using Git tag version: $VERSION_CLEAN"
          mvn versions:set -DnewVersion=$VERSION_CLEAN -DgenerateBackupPoms=false

      - name: Set build metadata
        run: |
          echo "Appending build info to manifest"
          echo "Implementation-Version: $VERSION" >> build.properties
          echo "Implementation-Build: $TIMESTAMP" >> build.properties

      - name: Deploy to Maven Central
        run: mvn -B deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
