name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.ref_name }}
      TIMESTAMP: ${{ github.run_id }}-${{ github.run_number }}-build${{ github.run_attempt }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      - name: Import GPG key
        run: echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create complete settings.xml for central publishing
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>central</id>
                <username>${{ secrets.OSSRH_USERNAME }}</username>
                <password>${{ secrets.OSSRH_PASSWORD }}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>ossrh</id>
                <properties>
                  <sonatypeHost>https://s01.oss.sonatype.org</sonatypeHost>
                  <publishRepoId>central</publishRepoId>
                  <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
                </properties>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>ossrh</activeProfile>
            </activeProfiles>
          </settings>
          EOF

      - name: Set version from tag
        run: |
          VERSION_CLEAN=${VERSION#v}
          echo "Using Git tag version: $VERSION_CLEAN"
          mvn versions:set -DnewVersion=$VERSION_CLEAN -DgenerateBackupPoms=false

      - name: Set build metadata
        run: |
          echo "Appending build info to manifest"
          echo "Implementation-Version: $VERSION" >> build.properties
          echo "Implementation-Build: $TIMESTAMP" >> build.properties

      - name: Deploy to Maven Central
        run: |
          VERSION_CLEAN=${VERSION#v}
          mvn -B deploy \
            -Dgpg.passphrase="${{ secrets.GPG_PASSPHRASE }}" \
            -DsonatypeHost=https://s01.oss.sonatype.org \
            -DpublishRepoId=central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

